version: '3.2'

services:
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'api'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '3306:3306'
      volumes:
        - my-db:/var/lib/mysql
    php:
        build: 
            dockerfile: Dockerfile
            context: .
        ports: 
            - '8080:80'
        volumes:
            - ./:/var/www/html 
volumes:
    my-db: